### ISSUE TITLE
Tarefas

### ISSUE THREAD

**Issue by LuCatstein** [vitorgripa/UNIMEP-ES-G05#1]
## // Apenas tarefas concluídas devem ser checadas no arquivo.

- [ ] Gerência de projetos
- [ ] Gerência de Configuração
- [ ] Engenharia de requisitos
- [ ] Verificação e validação
- [ ] Casos de uso
- [ ] Documentos de arquitetura
- [ ] Diagrama de componentes
- [ ] Diagrama de classes
- [ ] Código fonte
- [ ] Garantia de qualidade
- [ ] Templates
### (essa parte tava escrito na lousa mas não faço ideia se era parte das tarefas no trabalho)
- [ ] Planejamento
- [ ] Procedimentos

**Comment by cesariojr** [comment]
Revisar a issue e estruturar as atividades do grupo.
